# raas
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Raas
  # OrderResendCriteriaModel Model.
  class OrderResendCriteriaModel < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :new_email

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['new_email'] = 'newEmail'
      @_hash
    end

    def initialize(new_email = nil)
      @new_email = new_email
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      new_email = hash['newEmail']

      # Create object from extracted values.
      OrderResendCriteriaModel.new(new_email)
    end
  end
end
